repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    # -   id: trailing-whitespace
    # -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: debug-statements
# -   repo: https://github.com/sirwart/ripsecrets
    # rev: v0.1.8  # Use latest tag on GitHub
    # hooks:
    # -   id: ripsecrets
        # uncomment to check additional patterns
        # args:
        # - --additional-pattern 'mytoken*'
        # - --additional-pattern 'mykey*'
# after playing around, this seems to work as I would expect (detect token = "stuff")
-   repo: https://github.com/gitleaks/gitleaks
    rev: v8.16.1
    hooks:
      - id: gitleaks
